version: "3.9"

services:
  bot:
    build: .
    container_name: google-search-bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis-gsb
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
